MVC/Models/VeiculoImagemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class VeiculoImagemModel
    {
        public int ID { get; set; }
        public int IDVeiculo { get; set; }
        public string CaminhoImagem { get; set; }
    }
}

MVC/Models/VeiculoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    [Serializable]
    public class VeiculoModel
    {
        public int ID { get; set; }
                
        [Required(ErrorMessage = "O Campo PLACA é obrigatório")]
        [StringLength(8)]
        public string Placa { get; set; }

        [Required(ErrorMessage = "O Campo RENAVAM é obrigatório")]   
        [MinLength(9)]
        [MaxLength(11)]
        public string Renavam { get; set; }

        [Required(ErrorMessage = "O Campo NOME DO PROPRIETÁRIO é obrigatório")] 
        public string NomeProprietario { get; set; }

        [Required(ErrorMessage = "O Campo CPF é obrigatório")]
        [StringLength(11)]
        public string CPFProprietario { get; set; }

        public bool Bloqueado { get; set; }

        public List<VeiculoImagemModel> ListaImagens { get; set; }

    }
}

MVC/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using MVC.Models;
using MVC.DAO;
using System.IO;

namespace MVC.Controllers
{
    public class VeiculoController : Controller
    {  
        
        public ActionResult Index()
        {
            VeiculoBLL objVeiculoBLL = new VeiculoBLL();
            List<VeiculoModel> lst = objVeiculoBLL.ListaVeiculos("");

            return View(lst);
        }

        
        public ActionResult Details(int id)
        {
            VeiculoBLL objVeiculoBLL = new VeiculoBLL();
            VeiculoModel objVeic = objVeiculoBLL.SelecionarVeiculo(id);
            objVeic.ListaImagens = objVeiculoBLL.ListarImagensVeiculo(id);

            return View(objVeic);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Create(VeiculoModel model)
        {
            try
            {
                bool contemErros = false;

                if (!Util.ValidarCPF(model.CPFProprietario))
                {
                    ModelState.AddModelError("CPFProprietario", "CPF inválido !");
                    contemErros = true;
                }
                else
                {
                    ViewBag.CPF = "";
                }

                if (!Util.ValidaPlaca(model.Placa))
                {
                    ModelState.AddModelError("PLACA", "PLACA inválida !");
                    contemErros = true;
                }
                else
                {
                    ViewBag.PLACA = "";
                }

                if (contemErros)
                    return View(model);

                VeiculoBLL objVeiculoBLL = new VeiculoBLL();
                int ID = objVeiculoBLL.InserirVeiculo(model);
                List<VeiculoImagemModel> lstImagens = new List<VeiculoImagemModel>();

                if (Request.Files.Count > 0)
                {
                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        HttpPostedFileBase file = Request.Files[i];
                        string ext = Path.GetExtension(file.FileName);

                        if (Util.ExtensaoImagemValida(ext))
                        {
                            if (file.ContentLength < 500000)
                            {
                                string caminhoImagemSave = Server.MapPath("~/Imagens/") + file.FileName;

                                file.SaveAs(caminhoImagemSave);

                                VeiculoImagemModel objImagem = new VeiculoImagemModel();
                                objImagem.IDVeiculo = ID;
                                objImagem.CaminhoImagem = Path.GetFileName(caminhoImagemSave);

                                lstImagens.Add(objImagem);
                            }
                        }
                    }

                    objVeiculoBLL.InserirImagens(lstImagens);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Edit(int id)
        {
            VeiculoBLL objVeiculoBLL = new VeiculoBLL();
            VeiculoModel objVeic = objVeiculoBLL.SelecionarVeiculo(id);       

            return View(objVeic);
        }

        
        [HttpPost]
        public ActionResult Edit(int id, VeiculoModel model)
        {
            try
            {
                VeiculoBLL objVeiculoBLL = new VeiculoBLL();
                model.ID = id;

                objVeiculoBLL.AtualizarVeiculo(model);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }        
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Processo Seletivo Grupo Oxxy - Renato Bidóia</title>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fileuploader")

    @Styles.Render("~/Content/bxslider")

    @Scripts.Render("~/bundles/modernizr")

   

    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastro de Veículos", "Index", "Veiculo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Veiculo")</li>
                    <li>@Html.ActionLink("Cadastro", "Create", "Veiculo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cadastro de veículos - Processo Seletivo - Grupo Oxxy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/fileuploader")   
    @Scripts.Render("~/bundles/bxslider") 

    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Views/Veiculo/Create.cshtml
@model MVC.Models.VeiculoModel


@using (Html.BeginForm("Create", "Veiculo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadastrar Veículo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Placa:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control", @maxlength = "7" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })

                  
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Renavam:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control", @maxlength = "15" } })
                @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nome do Proprietário:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProprietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">CPF do Proprietário:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPFProprietario, new { htmlAttributes = new { @class = "form-control", @maxlength = "11" } })
                @Html.ValidationMessageFor(model => model.CPFProprietario, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bloqueado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Bloqueado)
                    @Html.ValidationMessageFor(model => model.Bloqueado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Carregar imagens
            </label>
            <div class="col-md-10">
                <input type="file" name="files">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/Veiculo/Details.cshtml
@model MVC.Models.VeiculoModel

<link href="~/Content/jquery.bxslider.css" rel="stylesheet" />

<script type="text/javascript">

    $(document).ready(function () {

        $('.bxSlider').bxSlider({
            mode: 'horizontal',
            minSlides: 2,
            maxSlides: 4,
            slideWidth: 248,
            preloadImages: 'all'
        });

    });

</script>

<div>
    <h4>Detalhes do Veículo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Fotos do Veículo</dt>

        <dd>
            <ul class="bxSlider">
                @foreach (var img in Model.ListaImagens)
                {
                    <li>
                        <img src="/Imagens/@img.CaminhoImagem" style="max-width: 225px;" />
                    </li>
                }
            </ul>
        </dd>
        <dt>
            <b>Placa:</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            <b>Renavam:</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Renavam)
        </dd>

        <dt>
            <b>Nome do Proprietário:</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeProprietario)
        </dd>

        <dt>
            <b>CPF do Proprietário:</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPFProprietario)
        </dd>

        <dt>
            <b>Bloqueado ?</b>
        </dt>

        <dd>
            @if (Model.Bloqueado)
            {
                <b>Sim</b>
            }
            else
            {
                <b>Não</b>
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar para Lista", "Index")
</p>

<script src="~/Scripts/jquery.bxslider.min.js"></script>

MVC/Views/Veiculo/Edit.cshtml
@model MVC.Models.VeiculoModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VeiculoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Renavam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeProprietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProprietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPFProprietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPFProprietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPFProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bloqueado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Bloqueado)
                    @Html.ValidationMessageFor(model => model.Bloqueado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/Veiculo/Index.cshtml
@model IEnumerable<MVC.Models.VeiculoModel>

<p>
    @Html.ActionLink("Cadastrar Novo Veículo", "Create")
</p>

<table class="table">
    <tr>
        <th>
            <b>Placa</b>
        </th>
        <th>
            <b>Renavam</b>
        </th>
        <th>
            <b>Nome do Proprietário</b>
        </th>
        <th>
            <b>CPF do Proprietário</b>
        </th>
        <th>
            <b>@Html.DisplayNameFor(model => model.Bloqueado)</b>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Renavam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeProprietario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPFProprietario)
            </td>
            <td>
                @if (item.Bloqueado)
                {
                    <b>Sim</b>
                }
                else
                {
                    <b>Não</b>
                }
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Visualizar", "Details", new { id = item.ID })
            </td>
        </tr>
    }

</table>